import Header from '@/components/root/header'
import './globals.css'
import { inter, lily_script_one, red_hat_display } from '@/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body className={`${lily_script_one.variable} ${inter.variable} ${red_hat_display.variable} bg-slate-100`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
